package com.lcwd.rating.entities;


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor

@Document("user_ratings")    // we are using @Document instead of @entity because we are using mongoDB not jpa hibernate
public class Rating {
    @Id //In mongo DB id is autogenerated we need not todo apart from this.
    private String ratingId;
    private String userId;
    private String hotelId;
    private int rating;
    private String feedback;


}
