server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8085




## pefrviously we are using below configuration but we are using the below configuration in multiple applications
## so we maintain the profiles on git and fetching using config server (config server fetch it from git) so we are using
## config server url (http://localhost:8085)


#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka



#------------------------------------------------------------------------------

## Implementing the actuator configuration for health check
## configure only health actuator

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: ALWAYS


## Resilience4j configuration

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


## Retry configuration
  retry:
    instances:
      ratingHotelService:
        maxAttempts: 3
        waitDuration: 5s


## Rate Limiter Configuration
  ratelimiter:
    instances:
      userRateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 0


