spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database : microservices
  application:
    name: RATING-SERVICE

  config:
    import: configserver:http://localhost:8085

server:
  port: 8083

## pefrviously we are using below configuration but we are using the below configuration in multiple applications
## so we maintain the profiles on git and fetching using config server (config server fetch it from git) so we are using
## config server url (http://localhost:8085)

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

